"""create game genre table

Revision ID: 0cdcb32a7eb8
Revises: 5b278c2a6ae8
Create Date: 2026-09-02 22:06:57.069446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdcb32a7eb8'
down_revision: Union[str, Sequence[str], None] = '5b278c2a6ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_genre',
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_game'], ['game.id_game'], ),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id_genre'], ),
    sa.PrimaryKeyConstraint('id_game', 'id_genre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_genre')
    # ### end Alembic commands ###
