"""create game table

Revision ID: 87159f84d1bd
Revises: 
Create Date: 2026-09-02 12:33:27.577210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87159f84d1bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('developer', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('opencritic_score', sa.Integer(), nullable=True),
    sa.CheckConstraint('opencritic_score >= 0 AND opencritic_score <= 100', name='ck_game_opencritic_score'),
    sa.PrimaryKeyConstraint('id_game')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
