"""create opencritic usage table

Revision ID: a92677b6a261
Revises: aefca3c396cf
Create Date: 2026-10-07 22:15:09.623913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92677b6a261'
down_revision: Union[str, Sequence[str], None] = 'aefca3c396cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opencritic_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('searches_limit', sa.Integer(), nullable=True),
    sa.Column('searches_remaining', sa.Integer(), nullable=True),
    sa.Column('searches_reset_at', sa.DateTime(), nullable=True),
    sa.Column('requests_limit', sa.Integer(), nullable=True),
    sa.Column('requests_remaining', sa.Integer(), nullable=True),
    sa.Column('requests_reset_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opencritic_usage')
    # ### end Alembic commands ###
