"""create collection item table

Revision ID: aefca3c396cf
Revises: da1e62993afc
Create Date: 2026-09-02 22:22:48.781324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefca3c396cf'
down_revision: Union[str, Sequence[str], None] = 'da1e62993afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_item',
    sa.Column('id_collection_item', sa.Integer(), nullable=False),
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('id_game_platform', sa.Integer(), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('starting_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.CheckConstraint("type IN ('Physical', 'Digital')", name='ck_collection_item_type'),
    sa.CheckConstraint('total_hours >= 0', name='ck_collection_item_total_hours'),
    sa.ForeignKeyConstraint(['id_game'], ['game.id_game'], ),
    sa.ForeignKeyConstraint(['id_game_platform'], ['game_platform.id_game_platform'], ),
    sa.PrimaryKeyConstraint('id_collection_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_item')
    # ### end Alembic commands ###
