"""create game platform table

Revision ID: da1e62993afc
Revises: 0cdcb32a7eb8
Create Date: 2026-09-02 22:17:10.352988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1e62993afc'
down_revision: Union[str, Sequence[str], None] = '0cdcb32a7eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_platform',
    sa.Column('id_game_platform', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_game_platform'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_platform')
    # ### end Alembic commands ###
